export const Constants = {
  DEFAULT_STORE_DELIMITER: '-',
  REDIS_CLIENT: 'REDIS_CLIENT',
  REDIS_CLIENT_STORE_SERVICE_SUFFIX: '_STORE_SERVICE',
  REDIS_REPOSITORY_SCHEMA: 'REDIS_REPOSITORY_SCHEMA'
};
