export const Constants = {
  ACCESS_CONTROL_MODULE_NAME: 'ACCESS_CONTROL_MODULE_NAME',
  DEFAULT_ACCESS_TOKEN_EXPIRY_TIME_IN_HOURS: 24,
  DEFAULT_ACCESS_TOKEN_STORAGE_TTL_MULTIPLIER: 1,
  DEFAULT_REFRESH_TOKEN_EXPIRY_TIME_IN_HOURS: 24,
  DEFAULT_REFRESH_TOKEN_STORAGE_TTL_MULTIPLIER: 1,
  DOMAIN_MODULE_NAME: 'DOMAIN_MODULE_NAME',
  OAUTH2_CODE_VERIFIER_LENGTH: '128',
  OAUTH2_PKCE_CHALLENGE_HASH_METHOD: 'SHA-256',
  TOKEN_EXPIRED_ERROR: 'jwt expired',
  TOKEN_MISMATCHED_AUDIENCES_ERROR: 'Mismatched audiences',
  TOKEN_MISMATCHED_ISSUER_ERROR: 'Mismatched issuer'
};
