export const Constants = {
  API_MODULE_AUTHORIZATION_SERVICE: 'API_MODULE_AUTHORIZATION_SERVICE',
  API_MODULE_NAME: 'API_MODULE_NAME',
  AUTHORIZATION_MIDDLEWARE_AUTHENTICATION_MANAGER_SERVICE:
    'AUTHORIZATION_MIDDLEWARE_AUTHENTICATION_MANAGER_SERVICE',
  AUTHORIZATION_MIDDLEWARE_TOKEN_MANAGER_SERVICE:
    'AUTHORIZATION_MIDDLEWARE_TOKEN_MANAGER_SERVICE',
  AUTHORIZATION_INTERCEPTOR: 'AUTHORIZATION_INTERCEPTOR',
  ERROR_INTERCEPTOR: 'ERROR_INTERCEPTOR',
  HTTP_EXCEPTION_FILTER: 'HTTP_EXCEPTION_FILTER'
};
