export const Constants = {
  RDB_ENTITY_REPOSITORY: 'RDB_ENTITY_REPOSITORY',
  RDB_REPOSITORY_CONNECTION_NAME: 'RDB_REPOSITORY_CONNECTION_NAME',
  RDB_REPOSITORY_DATASOURCE: 'RDB_REPOSITORY_DATASOURCE',
  RDB_REPOSITORY_ENTITY_CLASS: 'RDB_REPOSITORY_ENTITY_CLASS',
  SQL_BUILDER_DB_CONFIG_PATH: 'SQL_BUILDER_DB_CONFIG_PATH',
  SQL_BUILDER_SERVICE_TOKEN_SUFFIX: '_SQL_BUILDER_SERVICE'
};
